### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by Franky1** [DutchCryptoDad/bamboo-ta#1]
I stumbled across this library and wondered:

- Which **indicators** are offered by this library?
- How does this library _differ_ from e.g. the `pandas-ta` and `ta-lib` libraries?

**Comment by DutchCryptoDad** [comment]
Documentation is available in the docs directory. you can also reach this from the README.md file.
Since other libraries are not updated regularly and lag behind, I started to make this library. See the Readme for more info about that.
